# Generated by Django 5.1.2 on 2024-10-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.IntegerField(primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
            ],
        ),
    ]
