# Generated by Django 5.1.2 on 2025-05-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Unclaimed', 'Unclaimed'), ('Claimed', 'Claimed'), ('Lost', 'Lost')], default='Unclaimed', max_length=20),
        ),
    ]
