# Generated by Django 5.1.2 on 2025-05-06 00:29

from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('user', 'UserProfile')

    # Get all users
    users = User.objects.all()

    # For each user, check if they have a profile
    for user in users:
        # Check if a profile exists for this user
        if not UserProfile.objects.filter(user=user).exists():
            # If the profile doesn't exist, create one
            UserProfile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]
